version: '3'

services:
  bridge:
    image: douglara/chatwoot-botpress-bridge:1
    environment:
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=true
      - SECRET_KEY_BASE=82d58d3dfb91238b495a311eb8539edf5064784f1d58994679db8363ec241c745bef0b446bfe44d66cbf91a2f4e497d8f6b1ef1656e3f405b0d263a9617ac75e
      - BOTPRESS_ENDPOINT=http://34.221.158.211:3000
      - BOTPRESS_BOT_ID=teste
      - CHATWOOT_ENDPOINT=https://app.govchat.tech
      - CHATWOOT_BOT_TOKEN=mQTpvFwkGVNBWwifjXEBb1oe
    ports:
      - '3002:3000'